resources:
- name: myGitRepo
  type: GitRepo
  configuration: 
    gitProvider: githublsilvapvt
    path: lsilvapvt/jfrog-pipelines-samples
    branches:
      include: main

pipelines:
  - name: hello_world_pipeline
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: myGitRepo     # Trigger execution on code commit
      execution:
        onStart:
          - echo "prepare for main execution"
        onExecute:
          - echo "Hello World!"      
        onSuccess:
          - echo "Job well done!"
        onFailure:
          - echo "uh oh, something went wrong"
        onComplete:
          - echo "Cleaning up some stuff"

    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1               # Execute this step after the prior step
      execution:
        onStart:
          - echo "Getting onStart done"
        onExecute:
          - echo "Goodbye World!"
        onSuccess:
          - echo "Doing onSuccess!"
        onFailure:
          - echo "uh oh, something went wrong"
        onComplete:
          - echo "Doing the onComplete stuff."
