resources:
- name: rpGitRepo
  type: GitRepo
  configuration: 
    gitProvider: githublsilvapvt
    path: lsilvapvt/redis-probe
    branches:
      include: master

- name: rp_go_buildinfo
  type: BuildInfo
  configuration:
    sourceArtifactory: artifactorylucianos

- name: rpImage
  type: Image
  configuration:
    registry: artifactorylucianos
    sourceRepository: default-docker-virtual
    imageName: lucianos.jfrog.io/default-docker-virtual/redis-probe
    imageTag: latest
    autoPull: true

- name: rp_build_info
  type: BuildInfo
  configuration:
    sourceArtifactory: artifactorylucianos
    buildName: rp_build
    buildNumber: 1   
 
- name: rp_promoted_build_info
  type: BuildInfo
  configuration:
    sourceArtifactory: artifactorylucianos
    buildName: rp_build
    buildNumber: 1

pipelines:

  - name: redis_probe_pipeline
    steps:
      - name: redis_probe
        type: GoBuild
        configuration:
          sourceLocation: src/.
          # outputLocation: .
          outputFile: redis-probe-linux
          resolverRepo: default-go
          noRegistry: true
          inputResources:
            - name: rpGitRepo
          integrations:
            - name: artifactorylucianos
        # execution:
        #   onComplete:
        #     - add_run_files ${step_output_dir}/redis-probe-linux myfile 

      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: redis_probe
          targetRepository: default-go-local
          integrations:
            - name: artifactorylucianos

      # Publish the Go sample app build info. Docs at https://www.jfrog.com/confluence/display/JFROG/PublishBuildInfo
      - name: publish_go_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_go_binary
          outputResources:
            - name: rp_go_buildinfo

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: rp_group
          dockerFileLocation: "docker/."
          dockerFileName: Dockerfile
          dockerImageName: lucianos.jfrog.io/default-docker-virtual/redis-probe
          dockerImageTag: ${run_number}
          inputResources:
            - name: rpGitRepo
          inputSteps:
            - name: publish_go_build
          integrations:
            - name: artifactorylucianos
        execution:
          onStart:
            - restore_run_files output ${res_rpGitRepo_resourcePath}/go-output
            # - ls -la ${res_rpGitRepo_resourcePath}/go-output
            - cp ${res_rpGitRepo_resourcePath}/go-output/redis-probe-linux ${res_rpGitRepo_resourcePath}/docker/.
            # - ls -la ${res_rpGitRepo_resourcePath}/docker
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: rp_group
          targetRepository: default-docker-virtual
          integrations:
            - name: artifactorylucianos
          inputSteps:
            - name: docker_build
          outputResources:
            - name: rpImage

      - name: publish_rp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: rp_build_info

      # - name: promote_rp_build
      #   type: PromoteBuild
      #   configuration:
      #     targetRepository: demo-pipelines
      #     integrations:
      #       - name: artifactorylucianos
      #     inputResources:
      #       - name: rp_build_info
      #     outputResources:
      #       - name: rp_promoted_build_info


      # - name: step_1
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: docker_push
      #   execution:
      #     onStart:
      #       - echo "prepare for main execution"
      #     onExecute:
      #       - echo "Hello World!"      
      #     onSuccess:
      #       - echo "Job well done!"
      #     onFailure:
      #       - echo "uh oh, something went wrong"
      #     onComplete:
      #       - echo "Cleaning up some stuff"