resources:
- name: rpGitRepo
  type: GitRepo
  configuration: 
    gitProvider: githublsilvapvt
    path: lsilvapvt/redis-probe
    branches:
      include: master

- name: rpImage
  type: Image
  configuration:
    registry: artifactorylucianos
    sourceRepository: default-docker-virtual
    imageName: lucianos.jfrog.io/default-docker-virtual/redis-probe
    imageTag: latest
    autoPull: true

- name: rp_build_info
  type: BuildInfo
  configuration:
    sourceArtifactory: artifactorylucianos
    buildName: rp_build
    buildNumber: 1   
 
- name: rp_promoted_build_info
  type: BuildInfo
  configuration:
    sourceArtifactory: artifactorylucianos
    buildName: rp_build
    buildNumber: 1

pipelines:

  - name: redis_probe_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: rp_group
          dockerFileLocation: "docker/."
          dockerFileName: Dockerfile
          dockerImageName: lucianos.jfrog.io/default-docker-virtual/redis-probe
          dockerImageTag: ${run_number}
          inputResources:
            - name: rpGitRepo
          integrations:
            - name: artifactorylucianos
        execution:
          onStart:
            - ls -la 
            - pwd
            # echo "echo Hello" > ./docker/redis-probe-linux
            # - chmod 755 ./docker/redis-probe-linux
            # - cat ./docker/redis-probe-linux


      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: rp_group
          targetRepository: default-docker-virtual
          integrations:
            - name: artifactorylucianos
          inputSteps:
            - name: docker_build
          outputResources:
            - name: rpImage

      - name: publish_rp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: rp_build_info

      # - name: promote_rp_build
      #   type: PromoteBuild
      #   configuration:
      #     targetRepository: demo-pipelines
      #     integrations:
      #       - name: artifactorylucianos
      #     inputResources:
      #       - name: rp_build_info
      #     outputResources:
      #       - name: rp_promoted_build_info


      - name: step_1
        type: Bash
        configuration:
          inputSteps:
            - name: docker_push
        execution:
          onStart:
            - echo "prepare for main execution"
          onExecute:
            - echo "Hello World!"      
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1               # Execute this step after the prior step
        execution:
          onStart:
            - echo "Getting onStart done"
          onExecute:
            - echo "Goodbye World!"
          onSuccess:
            - echo "Doing onSuccess!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Doing the onComplete stuff."
