resources:
  - name: my_git_repository
    type: GitRepo
    configuration:
      gitProvider: acme_co_github
      path: lsilvapvt/jfrog-pipelines-samples
      branches:
        include: main


pipelines:
  - name: acme_co_01_hello_world
    steps:
      - name: Step1
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: my_git_repository
        execution:
          onExecute:
            - echo "Hello JFrog Pipelines!"
            - echo $res_my_git_repository_commitSha
            - add_run_variables current_runid=$run_id
            - add_run_variables commitSha=$res_my_git_repository_commitSha

      - name: Step2
        type: Bash
        configuration:
          inputSteps:
            - name: Step1
        execution:
          onExecute:
            # Demonstrates the availability of an env variable written to run state during Step1
            - echo $current_runid

